### ISSUE TITLE
Failed to pick channel; failed to connect to all addresses

### ISSUE THREAD

**Issue by CloudMarc** [GoogleCloudPlatform/vertex-ai-samples#118]
## Expected Behavior
In "Test your query" cell of notebook, a Match is expected to be returned

## Actual Behavior
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/tmp/ipykernel_19870/467153318.py in <module>
    108     request.float_val.append(val)
    109 
--> 110 response = stub.Match(request)
    111 response

~/.local/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    944         state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 
    948     def with_call(self,

~/.local/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    847             return state.response
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 
    851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1635211606.895231791","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3158,"referenced_errors":[{"created":"@1635211606.895230354","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>

## Steps to Reproduce the Problem

1. Run https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb - with appropriate changes for your project, region, etc.
1. Get all the way to "Test your query"
1. Observe that this code leads to the above error:
```
import match_service_pb2
import match_service_pb2_grpc

channel = grpc.insecure_channel("{}:10000".format(DEPLOYED_INDEX_SERVER_IP))
stub = match_service_pb2_grpc.MatchServiceStub(channel)
```
## Specifications

- Version: 
- Platform: JupyterLab on Google Vertex Notebook

**Comment by yinghsienwu** [comment]
Did you make sure  Notebookinstance is in the same VPC network (and region) you created?  See the WARNING in the matching_engine_for_indexing.ipynb.

WARNING: The match service gRPC API (to create online queries against your deployed index) has to be executed in a Google Cloud Notebook instance that is created with the following requirements:
In the same region as where your ANN service is deployed (for example, if you set REGION = "us-central1" as same as the tutorial, the notebook instance has to be in us-central1).
Make sure you select the VPC network you created for ANN service (instead of using the "default" one). That is, you will have to create the VPC network below and then create a new notebook instance that uses that VPC.
If you run it in the colab or a Google Cloud Notebook instance in a different VPC network or region, the gRPC API will fail to peer the network (InactiveRPCError).

**Comment by kweinmeister** [comment]
I'll go ahead and close the issue, as we haven't heard any response back. Please feel free to reopen if you have any more feedback to help troubleshoot. Thanks.
