### ISSUE TITLE
Matching Engine: Need to understand working of update_embeddings() method

### ISSUE THREAD

**Issue by Q-SudhirDeshmukh** [GoogleCloudPlatform/vertex-ai-samples#1316]
I am running following code two times

`
tree_ah_index = tree_ah_index.update_embeddings(
    contents_delta_uri=EMBEDDINGS_INCRIMENTAL_URI,
)
`

## Expected Behavior
 
Since EMBEDDINGS_INCRIMENTAL_URI is same for both the runs Vector count should be 1

## Actual Behavior

However, I am getting Vector count of 2. 
So even though both embedding and it's ID is same I am getting two separate index entries unless I include is_complete_overwrite=True

Can someone please help me understand this behaviour in detail ?

## Specifications

- Version: Class MatchingEngineIndex (1.19.0)
- Platform: aiplatform

**Comment by ivanmkc** [comment]
Hi, here is the update from the eng team.

> This is expected behavior.

When the user first call CreateIndex, and we will create a base Index. And if the user call UpdateIndex(or update_embeddings in the SDK) with is_complete_overwrite=True, we will rebuild the base Index with the data in the contents_delta_uri.

However, if the user didn't set is_complete_overwrite=True, we will not touch the base Index, but instead will build a secondary Index. And the vector count is the total count of both base and secondary Index which is why the user will see count=2. During query, we will query both Index and aggregate the result(for example, in the user's case, since both embedding have the same ID, only the one in the secondary Index will be returned).

We have another mechanism called compaction which will be triggered when the secondary Index is too big, during that time, the base Index and the secondary Index will be compacted into one Index which will be the new base. The user will see vector count changed to 1 after compaction.
