### ISSUE TITLE
Multi node ddp vertex job with custom container CUDA error : invalid device ordinal

### ISSUE THREAD

**Issue by entrpn** [GoogleCloudPlatform/vertex-ai-samples#1454]
The [notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb) for multi node ddp training with pytorch has an error when deployed with GPUs. I made it work by changing the task.py device line to use `cuda` instead of `cuda:rank`. See below:

```python
  if torch.cuda.is_available() and not args.no_cuda:
    #device = torch.device('cuda:{}'.format(args.rank))
    device = torch.device('cuda')
  else:
    device = torch.device('cpu')

## Expected Behavior

Training job should run with multi node GPU in Vertex AI.

## Actual Behavior

job throws error: 
`RuntimeError: CUDA error: invalid device ordinal`

## Steps to Reproduce the Problem

1. Follow the notebook steps and create the Vertex AI training job. The job will fail.
1. Look at logs in stackdriver to find `RuntimeError: CUDA error: invalid device ordinal`

## Specifications

- Version: torch==1.13.1, google-cloud-aiplatform==1.18.1
- Platform: linux

**Comment by andrewferlitsch** [comment]
assigning to notebook author

**Comment by gericdong** [comment]
@entrpn: thank you for the feedback. I will update the notebook with your solution.

**Comment by gericdong** [comment]
@entrpn: I looked into the notebook and found out that the notebook was designed to demonstrate PyTorch distributed training on CPU only. as indicated in the notebook title "PyTorch image classification multi-node distributed data parallel training on cpu using Vertex training with custom container" and the training code, e.g. --no-cuda. 

The training script was originally from PyTorch so it has some GPU related code but this notebook is not meant to be run on GPU. It's great that you have made it work for GPU but I think that it will need some other code changes in order to make the distributed training work on GPU completely.

To see how PyTorch distributed training work on multi-node multi process environment with GPU with Vertex AI, you can check sample code in another notebook: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb

Based on the above analysis, I think it'd be better to keep the notebook as in its original intent and use other notebook samples for GPU. As such, I will close this bug.

Thank you again for your feedback. Let me know if you have any questions.
