### ISSUE TITLE
Can't cancel LRO for batch ingestion after deleting entity type / featurestore

### ISSUE THREAD

**Issue by tamirbennatan** [GoogleCloudPlatform/vertex-ai-samples#18]
## Expected Behavior

Feature Store Batch Ingestion: I would expect to be able to cancel a batch ingestion job, either through the web UI or through the REST API.

## Actual Behavior

I tried to cancel the operations through the rest API and got the response: 

```
{
  "error": {
    "code": 400,
    "message": "Operation projects/<PROJECT_ID>/locations/us-central1/operations/<OPERATION_ID> is not cancellable.",
    "status": "FAILED_PRECONDITION"
  }
}
```
I tried to delete the entity type and then the featurestore in order to force the ingest job to stop, but it's still running. The only way I could get the LRO to stop was to delete the featurestore entirely, at which point it fails and gives the following error: 

```
Online serving currently unavailable, Please retry the request shortly or reach out to support upon continued failure.

```

## Steps to Reproduce the Problem

1. Create a featurestore and entity
1. start an LRO for batch ingest
1. Try and cancel it with REST API

**Comment by kweinmeister** [comment]
Thank you for filing this feature request. This Github repo is used for issues with Vertex AI Samples. We investigated and determined that the best fit for this feature request is in the Python SDK for Vertex AI. So that it is reviewed by the appropriate team, please feel free to re-file it with this repo here: [googleapis/python-aiplatform](https://github.com/googleapis/python-aiplatform). Thank you!
