### ISSUE TITLE
LLaMA PeFT finetuning ignores most TrainingArguments passed, for example batch size

### ISSUE THREAD

**Issue by ypapanik** [GoogleCloudPlatform/vertex-ai-samples#2397]
Background: I am trying to finetune LLaMa 2 with Peft with this [notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb) on Vertex AI.
## Expected Behavior
I am passing specific arguments, all coming from Huggingface [TrainingArguments](https://huggingface.co/docs/transformers/v4.34.1/en/main_classes/trainer#transformers.TrainingArguments) and expect the job to be run with this configuration. I am sharing my configuration below:
`{
  "workerPoolSpecs": [
    {
      "machineSpec": {
        "machineType": "n1-standard-16",
        "acceleratorType": "NVIDIA_TESLA_V100",
        "acceleratorCount": 2
      },
      "replicaCount": "1",
      "diskSpec": {
        "bootDiskType": "pd-ssd",
        "bootDiskSizeGb": 300
      },
      "containerSpec": {
        "imageUri": "us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-peft-train",
        "args": [
          "--task=causal-language-modeling-lora",
          "--pretrained_model_id=<REDACTED-PATH-TO-LLAMA-IN-GCS>",
          "--dataset_name=<REDACTED-PROPRIETARY-DATASET>",
          "--output_dir=<REDACTED-GCS-PATH>",
          "--lora_rank=16",
          "--lora_alpha=32",
          "--lora_dropout=0.05",
          "--warmup_steps=10",
          "--max_steps=-1",
          "--learning_rate=0.0001",
          "--precision_mode=float16",
          "--template=vertex_sample",
          "--num_train_epochs = 1",
          "--per_device_train_batch_size = 16",
          "--per_device_eval_batch_size = 16",
          "--gradient_accumulation_steps = 2",
          "--optim = paged_adamw_32bit",
          "--save_steps = 500",
          "--logging_steps = 500",
          "--weight_decay = 0.001",
          "--fp16 = True",
          "--bf16 = True",
          "--max_grad_norm = 0.3",
          "--group_by_length = False",
          "--lr_scheduler_type = cosine",
          "--evaluation_strategy = 'steps'",
          "--metric_for_best_model = 'eval_loss'",
          "--greater_is_better = False",
          "--eval_steps = 500",
          "--save_strategy = 'steps'"
        ],
        "env": [
......
`

## Actual Behavior
What happens, is that some of these values are ignored, for example, while I give a batch size of 16, I can confirm that while running, the logs show a batch size of 4. My hypothesis is that in the backend, probably the function `/diffusers/examples/vertex_vision_model_garden_peft/main.py`, ignores these arguments and passes some defaults. I had the same issue with `max_steps` a few days ago, but now this seems fixed.

## Steps to Reproduce the Problem

1. Run the code provided in the aforementioned notebook
2. Add a parameter from HF's TrainingArguments such as           "--per_device_train_batch_size = 16", that is different to the default.

## Specifications

- Version: 
- Platform: Vertex AI

**Comment by ypapanik** [comment]
I am tentatively adding @xiangxu-google as a reviewer, since they seem to maintain the notebook.

**Comment by andrewferlitsch** [comment]
reached out to SWE to triage

**Comment by xiangxu-google** [comment]
@genquan9 Can you take a look?

**Comment by KCFindstr** [comment]
Thanks for the report.

1. Please be aware that not all parameters of the `TrainingArguments` can be overridden by the docker flags. For example, `fp16`, `bf16`, `save_strategy`, `metric_for_best_model`, `evaluation_strategy`, `group_by_length`, `max_grad_norm` are not supported yet, and the optimizer should be passed as `--optimizer=<name>` instead of `--optim`. Currently, some training parameters are automatically determined; Please let us know if you really need to override them and we can add more flexibility as needed. Also, in future releases, we will provide better validation of the docker flags and fail on unrecognized flags.

2. The specific `--per_device_train_batch_size = 16` problem is due to malformed flags. The convention of CLI flags is either `--per_device_train_batch_size 16` or `--per_device_train_batch_size=16` (notice the spaces). If you pass `--per_device_train_batch_size = 16`, it means setting `--per_device_train_batch_size` to the string `=` and add an extra argument `16` unrelated to the flag. This malformed flag caused the default values to be used.

**Comment by andrewferlitsch** [comment]
@ypapanik A SWE responded to your question (see above). Do you need any more assistance?
